# -*- coding: utf-8 -*-
"""258.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OaAk_QwdKZls1JvJeaygZvVL6uUdyKC8
"""

print(dir(str))

a='hello world'
b=a.upper()
print(b)

a='Hello world'
b=a.swapcase()
print(b)

a= 'hello world'
b=a.replace('hello', 'hi')
print(b)

a= '1234'
b= a.isdigit()
print(b)

a= '12v34'
b= a.isdigit()
print(b)

a= range(10)
b= list(a)
print(b)

my_list = list(range(5,15,2))
print(my_list)

def add_numbers(a,b):
  result = a+b
  return result

result2 = add_numbers(10,2)
print(result2)

def add_numbers(a,b):
  result = a+b
  return result
print(add_numbers(654675,4966754))

def greet(name,greeting='hello'):
  print(f"{greeting}, {name}!")

def claculate_sum(*args):
  total = sum(args)
  return total
print("sum of 1,2,3:", claculate_sum(1,2,3))
print("sum of 1,2,3,4:", claculate_sum(1,2,3,4))

correct_usernme ='kamalesh37'
correct_passwowrd = '3773'
username = input("Enter your username:")
password = input("Enter your password:")
if username == correct_usernme and password == correct_passwowrd:
  print("Access granted")
else:
  print("Access denied")

correct_usernme ='kamalesh37'
correct_passwowrd = '3773'
username = input("Enter your username:")
password = input("Enter your password:")
if username == correct_usernme and password == correct_passwowrd:
  print("Access granted")
else:
  print("Access denied")

def calculate_circle_area(radius):
    pi = 3.14159
    area = pi * radius ** 2
    return area

radius = float(input("Enter the radius of the circle: "))
area = calculate_circle_area(radius)
print(f"The area of the circle with radius {radius} is {area:.2f}")

numbers = [12, 45, 7, 89, 23, 56]
largest = max(numbers)
smallest = min(numbers)
total = sum(numbers)
count = len(numbers)
average = total / count

print("Numbers List:", numbers)
print("Largest Number:", largest)
print("Smallest Number:", smallest)
print("Sum of Numbers:", total)
print("Number of Items:", count)
print("Average of Numbers:", average)