# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x3V2UZkTbXirQc4A4DBoldbNbwZla70l
"""

#list
list = ["apple", "banana", "cherry", "date"]
print(list[0])
print(list[-1])
print(list[1:3])

list = {"apple", "banana", "cherry", "date"}
list .add("elderberry")
list .remove("banana")
list .discard("fig")
for list  in fruits:
    print(list )

t=['a','b','c','d','e']
t[1:3]

t[:4]

t[3:]

t[:]

